name: Code Complexity Check
on: 
  pull_request:
  workflow_dispatch:
    inputs:
      threshold:
        description: 'Complexity threshold'
        required: true
        default: '15'
jobs:
  complexity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: miguelcsx/catchy@v1.0.3
        with:
          threshold: ${{ github.event.inputs.threshold }}
